package borrador.igu.compras;

import borrador.ParametroData;
import borrador.Parametro;
import igu.ventas.clientes.ClientesTableModel;
import javax.swing.border.LineBorder;
import util.MsgPanel;

/**
 *
 * @author Asullom
 */
public class ParametrosCompraPanel extends javax.swing.JPanel {

    ClientesTableModel clientesTableModel = new ClientesTableModel();

    public ParametrosCompraPanel() {
        initComponents();
        //table.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        //table.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        paintParams(1);
    }

    private void paintParams(int id) {
        Parametro p = ParametroData.getById(id);
        onza.setText(p.getOnza() + "");
        porc.setText(p.getPorc() + "");
        ley.setText(p.getLey() + "");
        sistema.setText(p.getSistema() + "");
        tc.setText(p.getTc() + "");
        precio_do.setText(p.getPrecio_do() + "");
        precio_so.setText(p.getPrecio_so() + "");

    }
     private void paintParamsSoloPrecios(int id) {
        Parametro p = ParametroData.getById(id);
        //onza.setText(p.getOnza() + "");
        //porc.setText(p.getPorc() + "");
        //ley.setText(p.getLey() + "");
        //sistema.setText(p.getSistema() + "");
       // tc.setText(p.getTc() + "");
        precio_do.setText(p.getPrecio_do() + "");
        precio_so.setText(p.getPrecio_so() + "");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        guardarButton = new igu.util.buttons.TheButton();
        footFormPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        onza = new javax.swing.JTextField();
        msgPanel1 = new util.MsgPanel();
        xxx = new javax.swing.JLabel();
        porc = new javax.swing.JTextField();
        porc1 = new javax.swing.JLabel();
        precio_so = new javax.swing.JTextField();
        porc2 = new javax.swing.JLabel();
        ley = new javax.swing.JTextField();
        sistemaxx = new javax.swing.JLabel();
        sistema = new javax.swing.JTextField();
        porc3 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        precio_do = new javax.swing.JTextField();
        precio_dovvvv = new javax.swing.JLabel();
        msgPanel2 = new util.MsgPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("PARÁMETROS DE COMPRA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(602, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        guardarButton.setText("ACTUALIZAR");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout footFormPanelLayout = new javax.swing.GroupLayout(footFormPanel);
        footFormPanel.setLayout(footFormPanelLayout);
        footFormPanelLayout.setHorizontalGroup(
            footFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footFormPanelLayout.setVerticalGroup(
            footFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ONZA");

        onza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        onza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onzaKeyReleased(evt);
            }
        });

        msgPanel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        xxx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xxx.setText("%");

        porc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        porc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                porcKeyReleased(evt);
            }
        });

        porc1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        porc1.setText("SOLES");

        precio_so.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precio_so.setEnabled(false);
        precio_so.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio_soKeyReleased(evt);
            }
        });

        porc2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        porc2.setText("LEY");

        ley.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ley.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                leyKeyReleased(evt);
            }
        });

        sistemaxx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sistemaxx.setText("SISTEMA");

        sistema.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sistema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sistemaKeyReleased(evt);
            }
        });

        porc3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        porc3.setText("TC");

        tc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcKeyReleased(evt);
            }
        });

        precio_do.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        precio_do.setEnabled(false);
        precio_do.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precio_doKeyReleased(evt);
            }
        });

        precio_dovvvv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precio_dovvvv.setText("DOLAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(onza, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xxx)
                    .addComponent(porc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porc2)
                    .addComponent(ley, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sistemaxx)
                    .addComponent(sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precio_do, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio_dovvvv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porc3)
                    .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porc1)
                    .addComponent(precio_so, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(msgPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(msgPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(porc1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(precio_so, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(porc2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ley, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onza, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(xxx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(sistemaxx)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(precio_dovvvv)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(precio_do, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(porc3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(msgPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(footFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:

        if (onza.getText().trim().isEmpty() || porc.getText().trim().isEmpty() || ley.getText().trim().isEmpty()
                || sistema.getText().trim().isEmpty() || tc.getText().trim().isEmpty()) {
            onza.requestFocus();
            onza.setBorder(new LineBorder(new java.awt.Color(255, 0, 0), 3));
            MsgPanel.error("Falta completar campos", true);

        } else {
            
            Parametro p = new Parametro();
            p.setId(1);
            p.setOnza(Double.parseDouble(onza.getText()));
            p.setPorc(Double.parseDouble(porc.getText()));
            p.setLey(Double.parseDouble(ley.getText()));
            p.setSistema(Double.parseDouble(sistema.getText()));
            p.setTc(Double.parseDouble(tc.getText()));

            int opcion = ParametroData.update(p);
            if (opcion != 0) {
                MsgPanel.success("Se han modificado los parámetros de compra");
                paintParams(1);
            }
            
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void onzaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onzaKeyReleased
        // TODO add your handling code here:
        if (!onza.getText().trim().isEmpty()) { //reset
            onza.setBorder(new LineBorder(new java.awt.Color(0, 0, 0), 1));
            MsgPanel.error("");
            
            Parametro p = new Parametro();
            p.setId(1);
            p.setOnza(Double.parseDouble(onza.getText()));
            p.setPorc(Double.parseDouble(porc.getText()));
            p.setLey(Double.parseDouble(ley.getText()));
            p.setSistema(Double.parseDouble(sistema.getText()));
            p.setTc(Double.parseDouble(tc.getText()));

            int opcion = ParametroData.update(p);
            if (opcion != 0) {
                MsgPanel.success("Se han modificado los parámetros de compra");
                paintParamsSoloPrecios(1);
            }
            
        } else {
            onza.setBorder(new LineBorder(new java.awt.Color(255, 0, 0), 3));
            MsgPanel.error("onza es requerido", true);
        }
    }//GEN-LAST:event_onzaKeyReleased

    private void porcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_porcKeyReleased
        // TODO add your handling code here:
        if (!porc.getText().trim().isEmpty()) { //reset
            porc.setBorder(new LineBorder(new java.awt.Color(0, 0, 0), 1));
            MsgPanel.error("");
            
            Parametro p = new Parametro();
            p.setId(1);
            p.setOnza(Double.parseDouble(onza.getText()));
            p.setPorc(Double.parseDouble(porc.getText()));
            p.setLey(Double.parseDouble(ley.getText()));
            p.setSistema(Double.parseDouble(sistema.getText()));
            p.setTc(Double.parseDouble(tc.getText()));

            int opcion = ParametroData.update(p);
            if (opcion != 0) {
                MsgPanel.success("Se han modificado los parámetros de compra");
                paintParamsSoloPrecios(1);
            }
            
        } else {
            porc.setBorder(new LineBorder(new java.awt.Color(255, 0, 0), 3));
            MsgPanel.error("porc es requerido", true);
        }
    }//GEN-LAST:event_porcKeyReleased

    private void leyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leyKeyReleased
        // TODO add your handling code here:
        if (!ley.getText().trim().isEmpty()) { //reset
            ley.setBorder(new LineBorder(new java.awt.Color(0, 0, 0), 1));
            MsgPanel.error("");
            
            Parametro p = new Parametro();
            p.setId(1);
            p.setOnza(Double.parseDouble(onza.getText()));
            p.setPorc(Double.parseDouble(porc.getText()));
            p.setLey(Double.parseDouble(ley.getText()));
            p.setSistema(Double.parseDouble(sistema.getText()));
            p.setTc(Double.parseDouble(tc.getText()));

            int opcion = ParametroData.update(p);
            if (opcion != 0) {
                MsgPanel.success("Se han modificado los parámetros de compra");
                paintParamsSoloPrecios(1);
            }
            
        } else {
            ley.setBorder(new LineBorder(new java.awt.Color(255, 0, 0), 3));
            MsgPanel.error("ley es requerido", true);
        }
    }//GEN-LAST:event_leyKeyReleased

    private void sistemaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sistemaKeyReleased
        // TODO add your handling code here:
        if (!sistema.getText().trim().isEmpty()) { //reset
            sistema.setBorder(new LineBorder(new java.awt.Color(0, 0, 0), 1));
            MsgPanel.error("");
            
            Parametro p = new Parametro();
            p.setId(1);
            p.setOnza(Double.parseDouble(onza.getText()));
            p.setPorc(Double.parseDouble(porc.getText()));
            p.setLey(Double.parseDouble(ley.getText()));
            p.setSistema(Double.parseDouble(sistema.getText()));
            p.setTc(Double.parseDouble(tc.getText()));

            int opcion = ParametroData.update(p);
            if (opcion != 0) {
                MsgPanel.success("Se han modificado los parámetros de compra");
                paintParamsSoloPrecios(1);
            }
            
        } else {
            sistema.setBorder(new LineBorder(new java.awt.Color(255, 0, 0), 3));
            MsgPanel.error("sistema es requerido", true);
        }
    }//GEN-LAST:event_sistemaKeyReleased

    private void tcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcKeyReleased
        // TODO add your handling code here:
        if (!tc.getText().trim().isEmpty()) { //reset
            tc.setBorder(new LineBorder(new java.awt.Color(0, 0, 0), 1));
            MsgPanel.error("");
            
            Parametro p = new Parametro();
            p.setId(1);
            p.setOnza(Double.parseDouble(onza.getText()));
            p.setPorc(Double.parseDouble(porc.getText()));
            p.setLey(Double.parseDouble(ley.getText()));
            p.setSistema(Double.parseDouble(sistema.getText()));
            p.setTc(Double.parseDouble(tc.getText()));

            int opcion = ParametroData.update(p);
            if (opcion != 0) {
                MsgPanel.success("Se han modificado los parámetros de compra");
                paintParamsSoloPrecios(1);
            }
            
        } else {
            tc.setBorder(new LineBorder(new java.awt.Color(255, 0, 0), 3));
            MsgPanel.error("tc es requerido", true);
        }
    }//GEN-LAST:event_tcKeyReleased

    private void precio_soKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio_soKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_soKeyReleased

    private void precio_doKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precio_doKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_doKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footFormPanel;
    private igu.util.buttons.TheButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField ley;
    private util.MsgPanel msgPanel1;
    private util.MsgPanel msgPanel2;
    private javax.swing.JTextField onza;
    private javax.swing.JTextField porc;
    private javax.swing.JLabel porc1;
    private javax.swing.JLabel porc2;
    private javax.swing.JLabel porc3;
    private javax.swing.JTextField precio_do;
    private javax.swing.JLabel precio_dovvvv;
    private javax.swing.JTextField precio_so;
    private javax.swing.JTextField sistema;
    private javax.swing.JLabel sistemaxx;
    private javax.swing.JTextField tc;
    private javax.swing.JLabel xxx;
    // End of variables declaration//GEN-END:variables
}
